# Author: Beatriz Molina Muñiz (GitHub: @Beatriz-MM)
# Last modified: 03/04/2025
# Description: Export URLs from a JSON file of Instagram posts, generated by filter_json_posts.py, to a text file.
# Python version: 3.10.12

import json
import os

# IMPORTANT: Insert correct paths
json_path = "" # Example: "~/Posts/filtered_data.json"
destination_path = "" # Example: "~/Comentarios/urls_comentarios/"

# Specify encoding="utf-8" to correctly read the JSON file in Galician and Spanish
with open(json_path, "r", encoding="utf-8") as file:
    data = json.load(file)

# Count the total number of original URLs
total_original_urls = 0

for item in data:
    if 'url' in item:
        total_original_urls += 1
print("Total original URLs: ", total_original_urls )


# Count the URLs written in the current file
written_urls = 0

# Count the number of created files (starts at 1 because file numbering begins from 1)
current_file = 1

for item in data:
    if 'url' in item:
        url = item['url']

        # If the number of written URLs is a multiple of 1000, create a new file
        if written_urls % 1000 == 0:
            file_name = f"urls_{current_file}.txt"
            file_path = os.path.join(destination_path, file_name)
            current_file += 1
            written_urls = 0

            if os.path.exists(file_path):
                os.remove(file_path)
        
        # Append the URL to the current file
        with open(file_path, 'a') as file:
            file.write(url + '\n')
            written_urls += 1
print("The URLs have been saved in separate files")


# Verify if all URLs from the original file are present in the text files
total_written_urls = 0

for i in range(1, current_file):
    file_name = f"urls_{i}.txt"
    file_path = os.path.join(destination_path, file_name)
    with open(file_path, 'r') as file:
        urls = file.readlines()
        total_written_urls += len(urls)
print("Total written URLs: ", total_written_urls )

if total_original_urls == total_written_urls:
    print("All URLs from the original file have been successfully saved")
else:
    print("ERROR! Some URLs might be missing in the text files")